services:
  rabbitmq:
    container_name: rabbitmq
    hostname: rabbitmq
    image: rabbitmq:latest
    ports:
      - "5672:5672"   # Default connection
      - "15672:15672" # Default Management
    networks:
      - ict3102_default
  app:
    # image: jaspzx/3102:latest
    build: .
    container_name: app
    depends_on:
      - db
      - rabbitmq
      - vqa
    links:
      - db
      - rabbitmq
      - vqa
    ports:
      - "5000:5000"
    networks:
      - ict3102_default
    command: ["./wait-for-it.sh","rabbitmq:5672","--","python","app.py"]
  vqa:
    build: .
    container_name: vqa
    depends_on:
      - db
      - rabbitmq
    networks:
      - ict3102_default
    command: ["./wait-for-it.sh","rabbitmq:5672" ,"--","python","./VQA/main.py"]
  questgen:
    build: .
    container_name: questgen
    depends_on:
      - db
      - rabbitmq
    networks:
      - ict3102_default
    command: ["./wait-for-it.sh","rabbitmq:5672" ,"--","python","./questGen/main.py"]
  db:
    container_name: db
    hostname: db
    image: mysql:5.7
    # image: jaspzx/3102db:latest
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      # MYSQL_DATABASE: 02db
    volumes:
      # - ./db:/docker-entrypoint-initdb.d/:ro
      # - ./db:/var/lib/mysql:rw
      - ./db:/docker-entrypoint-initdb.d/:rw
    networks:
      - ict3102_default
networks:
  ict3102_default:
    driver: bridge
