# Use an official Python runtime as an image
FROM python:3.7

# The EXPOSE instruction indicates the ports on which a container
EXPOSE 5000
EXPOSE 3306

# Sets the working directory for following COPY and CMD instructions
# Notice we haven’t created a directory by this name - this instruction
# creates a directory with this name if it doesn’t exist
WORKDIR /app

COPY ./flask_app /app
# COPY init.sql docker-entrypoint-initdb.d/init.sql
ADD ./db/init.sql /docker-entrypoint-initdb.d

RUN python -m pip install --upgrade pip
RUN pip install --trusted-host pypi.org --trusted-host pypi.python.org --trusted-host=files.pythonhosted.org --no-cache-dir -r ./requirements.txt
RUN dir /app
# CMD python -m flask --app app run
CMD ["./app/wait-for-it.sh","rabbitmq:5672"]
CMD ["python", "-m" , "flask", "run", "--host=0.0.0.0"]