FROM python:3.7

WORKDIR /app/VQA

# Run main.py when the container launches
COPY ./VQA /app/VQA
RUN curl -LJO https://storage.googleapis.com/sfr-vision-language-research/BLIP/models/model_base_capfilt_large.pth
RUN curl -LJO https://storage.googleapis.com/sfr-vision-language-research/BLIP/models/model_base_vqa_capfilt_large.pth
RUN pip install -U pip setuptools wheel
RUN pip install --prefer-binary -r ./requirements.txt
CMD ["python", "-u", "main.py"]