FROM python:latest

WORKDIR /app/VQA

# RUN python -m pip install --upgrade pip
# RUN pip install --trusted-host pypi.org --trusted-host pypi.python.org --trusted-host=files.pythonhosted.org --no-cache-dir -r requirements.txt

# Run main.py when the container launches
COPY . .
CMD python main.py