FROM python:3.7

WORKDIR /app/VQA

# RUN python -m pip install --upgrade pip

# Run main.py when the container launches
COPY ./VQA /app/VQA
RUN pip install --trusted-host pypi.org --trusted-host pypi.python.org --trusted-host=files.pythonhosted.org --no-cache-dir -r requirements.txt
CMD python main.py