# Import Module
import os

# Folder Path
path = "./TestResults"


# Read text File


def read_text_file(file_path):
    with open(file_path, 'r') as f:
        result = f.readlines()[0:2]
        charNum = ''.join(filter(lambda i: i.isdigit(), result[0]))
        queGen = ''.join(filter(lambda i: i.isdigit(), result[1]))
    return [charNum, queGen]

captions = 0
questions = 0
characters = 0

# iterate through all file
for file in os.listdir(path):
    # Check whether file is in text format or not
    if file.endswith(".txt"):
        file_path = f"{path}/{file}"
        captions += 1
        # call read text file function
        result = read_text_file(file_path)
        questions += int(result[1])
        characters += int(result[0])

print("TotalCaption: "+str(captions))
print("TotalQnsGenerated: "+str(questions))
print("Avg No. of Questions Generated by Characters: "+str(characters/questions))
