FROM python:3.10.8-bullseye

WORKDIR /app/questGen

# Run main.py when the container launches

COPY requirements.txt requirements.txt
RUN pip install -r requirements.txt --no-cache-dir
RUN python -m nltk.downloader punkt

COPY . .
CMD python main.py