FROM python:latest

WORKDIR /app/questGen

# Run main.py when the container launches

COPY requirements.txt requirements.txt
RUN python -m pip install --upgrade pip
RUN pip install -r requirements.txt


COPY . .
CMD python main.py