FROM python:3.10.8-bullseye

WORKDIR /app/questGen

# Run main.py when the container launches
COPY . .

RUN pip install -r requirements.txt
RUN #python -m nltk.downloader punkt

# copy origin destination

